// Hardhat is used only as a local JSON-RPC node for integration tests.
// Production artifacts are generated by scripts/compile.mjs.

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: {
    version: "0.8.24",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      // The contracts do not require Cancun-only opcodes. Paris is a
      // conservative local target compatible with ARC's documented Osaka
      // execution baseline.
      evmVersion: "paris",
    },
  },
  networks: {
    hardhat: {},
  },
};
